language: objective-c
osx_image: xcode8.2
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/ # Execute tests for every tag with name in format "1.2.3"
    - develop
script:
  - xcodebuild test -project Clue/Clue.xcodeproj -scheme ClueTests -destination "platform=macOS,arch=x86_64" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
